//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoClient.Communication {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Communication.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name xmlFormatCommand from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Command", ReplyAction="*")]
        AutoClient.Communication.CommandResponse Command(AutoClient.Communication.CommandRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CommandRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Command", Namespace="http://tempuri.org/", Order=0)]
        public AutoClient.Communication.CommandRequestBody Body;
        
        public CommandRequest() {
        }
        
        public CommandRequest(AutoClient.Communication.CommandRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CommandRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlFormatCommand;
        
        public CommandRequestBody() {
        }
        
        public CommandRequestBody(string xmlFormatCommand) {
            this.xmlFormatCommand = xmlFormatCommand;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CommandResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CommandResponse", Namespace="http://tempuri.org/", Order=0)]
        public AutoClient.Communication.CommandResponseBody Body;
        
        public CommandResponse() {
        }
        
        public CommandResponse(AutoClient.Communication.CommandResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CommandResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CommandResult;
        
        public CommandResponseBody() {
        }
        
        public CommandResponseBody(string CommandResult) {
            this.CommandResult = CommandResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : AutoClient.Communication.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<AutoClient.Communication.ServiceSoap>, AutoClient.Communication.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoClient.Communication.CommandResponse AutoClient.Communication.ServiceSoap.Command(AutoClient.Communication.CommandRequest request) {
            return base.Channel.Command(request);
        }
        
        public string Command(string xmlFormatCommand) {
            AutoClient.Communication.CommandRequest inValue = new AutoClient.Communication.CommandRequest();
            inValue.Body = new AutoClient.Communication.CommandRequestBody();
            inValue.Body.xmlFormatCommand = xmlFormatCommand;
            AutoClient.Communication.CommandResponse retVal = ((AutoClient.Communication.ServiceSoap)(this)).Command(inValue);
            return retVal.Body.CommandResult;
        }
    }
}
